//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputConrolls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputConrolls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputConrolls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputConrolls"",
    ""maps"": [
        {
            ""name"": ""New action map"",
            ""id"": ""86edf822-4014-4cca-bce0-ca343249234c"",
            ""actions"": [
                {
                    ""name"": ""MyTouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""c1e9c5ba-765f-4e10-8d09-aae2cad33b20"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MyTouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""33e111ab-362b-47bd-b147-ca8f3679e083"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""New action"",
                    ""type"": ""Value"",
                    ""id"": ""e70fa93e-a157-4ce1-8fe3-1509aae37f59"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24f6784f-8ace-4947-b5dd-c2d2b9134b49"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MyTouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24d0f66b-b8af-4bf6-a94b-8dbb90086a68"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MyTouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32c807bc-0ec4-4842-8e24-f8799dd78f5e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // New action map
        m_Newactionmap = asset.FindActionMap("New action map", throwIfNotFound: true);
        m_Newactionmap_MyTouchPosition = m_Newactionmap.FindAction("MyTouchPosition", throwIfNotFound: true);
        m_Newactionmap_MyTouchPress = m_Newactionmap.FindAction("MyTouchPress", throwIfNotFound: true);
        m_Newactionmap_Newaction = m_Newactionmap.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // New action map
    private readonly InputActionMap m_Newactionmap;
    private List<INewactionmapActions> m_NewactionmapActionsCallbackInterfaces = new List<INewactionmapActions>();
    private readonly InputAction m_Newactionmap_MyTouchPosition;
    private readonly InputAction m_Newactionmap_MyTouchPress;
    private readonly InputAction m_Newactionmap_Newaction;
    public struct NewactionmapActions
    {
        private @InputConrolls m_Wrapper;
        public NewactionmapActions(@InputConrolls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MyTouchPosition => m_Wrapper.m_Newactionmap_MyTouchPosition;
        public InputAction @MyTouchPress => m_Wrapper.m_Newactionmap_MyTouchPress;
        public InputAction @Newaction => m_Wrapper.m_Newactionmap_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Newactionmap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NewactionmapActions set) { return set.Get(); }
        public void AddCallbacks(INewactionmapActions instance)
        {
            if (instance == null || m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Add(instance);
            @MyTouchPosition.started += instance.OnMyTouchPosition;
            @MyTouchPosition.performed += instance.OnMyTouchPosition;
            @MyTouchPosition.canceled += instance.OnMyTouchPosition;
            @MyTouchPress.started += instance.OnMyTouchPress;
            @MyTouchPress.performed += instance.OnMyTouchPress;
            @MyTouchPress.canceled += instance.OnMyTouchPress;
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(INewactionmapActions instance)
        {
            @MyTouchPosition.started -= instance.OnMyTouchPosition;
            @MyTouchPosition.performed -= instance.OnMyTouchPosition;
            @MyTouchPosition.canceled -= instance.OnMyTouchPosition;
            @MyTouchPress.started -= instance.OnMyTouchPress;
            @MyTouchPress.performed -= instance.OnMyTouchPress;
            @MyTouchPress.canceled -= instance.OnMyTouchPress;
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(INewactionmapActions instance)
        {
            if (m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INewactionmapActions instance)
        {
            foreach (var item in m_Wrapper.m_NewactionmapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NewactionmapActions @Newactionmap => new NewactionmapActions(this);
    public interface INewactionmapActions
    {
        void OnMyTouchPosition(InputAction.CallbackContext context);
        void OnMyTouchPress(InputAction.CallbackContext context);
        void OnNewaction(InputAction.CallbackContext context);
    }
}
